version: '3.3'

services: 
    wordpress:
        build: .docker/wordpress/.
        restart: always
        ports: 
            - 80:80
        environment: 
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wpuser
            WORDPRESS_DB_PASSWORD: wppass
            WORDPRESS_DB_NAME: wpdb
        volumes: 
            - ./src:/var/www/html
            - ./apache2/log:/var/log/apache2

    db:
        image: mysql:5.7
        restart: always
        ports:
            - 3300:3306
        environment:
            MYSQL_DATABASE: wpdb
            MYSQL_USER: wpuser
            MYSQL_PASSWORD: wppass
            MYSQL_ROOT_PASSWORD: root
        volumes: 
            - db:/var/lib/mysql

    adminer:
        depends_on: 
            - db
        image: adminer
        restart: always
        ports: 
            - 8080:8080

networks: 
    back:
        
volumes: 
    db: