#!/usr/bin/env bash
sudo service apache2 stop
docker-compose up -d && \
echo "
================ 🚀 Iniciando 🚀 ===================
      
      Links de Acesso:

      🌎 Web server:   http://localhost
      ⚙️  Adminer:      http://localhost:8080

================ 🚀 -------- 🚀 ==================="